#!/usr/bin/env bash
set -euo pipefail

# promote-to-main.sh — dev ブランチから main へのプロモーション
# .mainignore に記載されたファイルを除外し、PR を作成する

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MAINIGNORE="$PROJECT_ROOT/.mainignore"
REMOTE="${REMOTE:-origin}"
MAIN_BRANCH="main"
DEV_BRANCH="dev"

# --- ヘルパー ---

die() { echo "ERROR: $1" >&2; exit 1; }

usage() {
  cat <<USAGE
Usage: $(basename "$0") [OPTIONS]

dev ブランチから main へのプロモーション PR を作成する。
.mainignore に記載されたファイルを除外した一時ブランチを作り、PR を開く。

Options:
  --dry-run    実際の push/PR 作成を行わず、除外されるファイルを表示する
  --no-pr      push のみ行い、PR は作成しない（初回 push 用）
  -h, --help   このヘルプを表示する
USAGE
}

# --- 引数解析 ---

DRY_RUN=false
NO_PR=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)  DRY_RUN=true; shift ;;
    --no-pr)    NO_PR=true; shift ;;
    -h|--help)  usage; exit 0 ;;
    *)          die "Unknown option: $1" ;;
  esac
done

# --- 前提チェック ---

cd "$PROJECT_ROOT"

[[ -f "$MAINIGNORE" ]] || die ".mainignore が見つかりません: $MAINIGNORE"

CURRENT_BRANCH="$(git branch --show-current)"
[[ "$CURRENT_BRANCH" == "$DEV_BRANCH" ]] || die "dev ブランチで実行してください（現在: $CURRENT_BRANCH）"

if [[ -n "$(git status --porcelain)" ]]; then
  die "未コミットの変更があります。先にコミットしてください。"
fi

# --- .mainignore の読み込み ---

REMOVE_PATHS=()
while IFS= read -r line; do
  # コメントと空行をスキップ
  [[ -z "$line" || "$line" == \#* ]] && continue
  REMOVE_PATHS+=("$line")
done < "$MAINIGNORE"

echo "=== promote-to-main ==="
echo "除外対象: ${#REMOVE_PATHS[@]} パス"

if $DRY_RUN; then
  echo ""
  echo "--- dry-run: 除外されるファイル ---"
  for path in "${REMOVE_PATHS[@]}"; do
    if [[ -e "$path" ]]; then
      echo "  [exists] $path"
    else
      echo "  [skip]   $path (not found)"
    fi
  done
  echo ""
  echo "dry-run 完了。実際の変更は行いませんでした。"
  exit 0
fi

# --- 一時ブランチの作成 ---

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
PROMOTE_BRANCH="promote/main-${TIMESTAMP}"

echo "一時ブランチを作成: $PROMOTE_BRANCH"
git checkout -b "$PROMOTE_BRANCH"

# --- dev-only ファイルの除外 ---

REMOVED=0
for path in "${REMOVE_PATHS[@]}"; do
  if git ls-files --error-unmatch "$path" &>/dev/null 2>&1; then
    git rm -rf --quiet "$path"
    ((REMOVED++))
    echo "  removed: $path"
  elif [[ -d "$path" ]] && git ls-files "$path" | grep -q .; then
    git rm -rf --quiet "$path"
    ((REMOVED++))
    echo "  removed: $path"
  else
    echo "  skipped: $path (not tracked)"
  fi
done

echo "除外完了: $REMOVED パス"

if [[ "$REMOVED" -eq 0 ]]; then
  echo "除外するファイルがありませんでした。"
  git checkout "$DEV_BRANCH"
  git branch -D "$PROMOTE_BRANCH"
  exit 0
fi

# --- コミット ---

git commit -m "chore: promote dev to main — dev-only ファイルを除外"

# --- push ---

echo "push: $PROMOTE_BRANCH → $REMOTE"
git push -u "$REMOTE" "$PROMOTE_BRANCH"

# --- PR 作成 ---

if $NO_PR; then
  echo ""
  echo "=== push 完了 ==="
  echo "ブランチ: $PROMOTE_BRANCH"
  echo "PR は作成していません（--no-pr）"
  echo ""
  echo "main への反映:"
  echo "  git checkout main && git merge $PROMOTE_BRANCH && git push $REMOTE main"
else
  echo "PR を作成..."
  PR_URL=$(gh pr create \
    --base "$MAIN_BRANCH" \
    --head "$PROMOTE_BRANCH" \
    --title "Promote dev to main" \
    --body "$(cat <<'BODY'
## Summary

dev ブランチの変更を main にプロモーション。
`.mainignore` に記載された dev-only ファイルを除外済み。

---
Generated by `scripts/promote-to-main.sh`
BODY
)")
  echo ""
  echo "=== PR 作成完了 ==="
  echo "$PR_URL"
fi

# --- CI 待機 + ブランチ削除 ---

if ! $NO_PR; then
  echo ""
  echo "CI の完了を待機中..."
  PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]*$')
  if gh pr checks "$PR_NUMBER" --watch; then
    echo "CI パス ✓"
  else
    echo "CI 失敗 — ブランチを残します。修正後に再実行してください。"
    git checkout "$DEV_BRANCH"
    exit 1
  fi
fi

# --- dev に戻る + 一時ブランチ削除 ---

git checkout "$DEV_BRANCH"
git branch -d "$PROMOTE_BRANCH"
echo "dev ブランチに戻りました。一時ブランチ $PROMOTE_BRANCH を削除しました。"
